# Generated by Django 4.0.1 on 2022-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial',
            name='actors',
            field=models.ManyToManyField(blank=True, to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, to='actors.Actor'),
        ),
    ]
